load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "avro_c",
    build_file = "//third_party:avro_c.BUILD",
    sha256 = "77c679a53f524aedf917425030830ee46897981a43bf6aa25943683d7184665f",
    strip_prefix = "avro-release-1.9.0.1/lang/c/src",
    urls = [
        "https://github.com/erwa/avro/archive/release-1.9.0.1.tar.gz"
    ],
)

http_archive(
    name = "avro",
    build_file = "//third_party:avro.BUILD",
    patch_args = ["-p1"],
    #patches = [
    #    "//third_party:avro.patch",
    #],
    sha256 = "42fbe407263ec174d448121cd0e20adcd75c43cb9f192b97476d9b99fa69faf3",
    strip_prefix = "avro-release-1.9.0-rc4/lang/c++",
    urls = [
        "https://mirror.bazel.build/github.com/apache/avro/archive/release-1.9.0-rc4.tar.gz",
        "https://github.com/apache/avro/archive/release-1.9.0-rc4.tar.gz",
    ],
)

http_archive(
    name = "boost",
    build_file = "//third_party:boost.BUILD",
    sha256 = "8aa4e330c870ef50a896634c931adf468b21f8a69b77007e45c444151229f665",
    strip_prefix = "boost_1_67_0",
    urls = [
        "https://mirror.bazel.build/dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz",
        "https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz",
        "https://downloads.sourceforge.net/project/boost/boost/1.67.0/boost_1_67_0.tar.gz",
    ],
)

http_archive(
    name = "com_github_madler_zlib",
    build_file = "//third_party:zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = [
        "https://mirror.bazel.build/zlib.net/zlib-1.2.11.tar.gz",
        "https://zlib.net/zlib-1.2.11.tar.gz",
    ],
)